import os

SCALE = 1

TILE_SIZE = 32
HALF_TILE = TILE_SIZE / 2

GAME_WIDTH = 16 * TILE_SIZE
GAME_HEIGHT = 9 * TILE_SIZE

ANTI_ALIASING = os.getenv("ANTI_ALIASING", "false").lower() == "true"
DEFAULT_FPS = 120
